build.gradle
src/main/java/com/quokka/classmate/config/WebSecurityConfig.java
src/main/java/com/quokka/classmate/controller/StudentController.java
src/main/java/com/quokka/classmate/domain/TempDomain.java
src/main/java/com/quokka/classmate/domain/dto/StudentRequestDto.java
src/main/java/com/quokka/classmate/domain/entity/Student.java
src/main/java/com/quokka/classmate/global/config/WebSecurityConfig.java
src/main/java/com/quokka/classmate/repository/StudentRepository.java
src/main/java/com/quokka/classmate/repository/TempRepository.java
src/main/java/com/quokka/classmate/service/StudentService.java
src/main/java/com/quokka/classmate/service/TempService.java

Feature lsh student

---

.gitignore
build.gradle
src/main/java/com/quokka/classmate/controller/HomeController.java
src/main/java/com/quokka/classmate/controller/StudentController.java
src/main/java/com/quokka/classmate/controller/TempController.java
src/main/java/com/quokka/classmate/domain/dto/StudentLoginRequestDto.java
src/main/java/com/quokka/classmate/domain/dto/StudentSignUpRequestDto.java
src/main/java/com/quokka/classmate/domain/entity/Role.java
src/main/java/com/quokka/classmate/domain/entity/Student.java
src/main/java/com/quokka/classmate/global/TempGlobal.java
src/main/java/com/quokka/classmate/global/config/WebSecurityConfig.java
src/main/java/com/quokka/classmate/global/jwt/JwtUtil.java
src/main/java/com/quokka/classmate/global/security/JwtAuthenticationFilter.java
src/main/java/com/quokka/classmate/global/security/JwtAuthorizationFilter.java
src/main/java/com/quokka/classmate/global/security/UserDetailsImpl.java
src/main/java/com/quokka/classmate/global/security/UserDetailsServiceImpl.java
src/main/java/com/quokka/classmate/service/StudentService.java
src/main/resources/application.yml
src/main/resources/static/css/login.css
src/main/resources/static/css/signup.css
src/main/resources/templates/login.html
src/main/resources/templates/main.html
src/main/resources/templates/signup.html

1. 스프링 시큐리티 적용
2. JWT 로그인 구현
3. 회원가입 구현
로그인 및 회원가입 구현하였습니다.
추가적으로 application.yml gitignore에 추가하였습니다.

Feature ksy login and signup

---

src/main/java/com/quokka/classmate/repository/SubjectRepository.java
src/main/java/com/quokka/classmate/service/SubjectService.java

fix: 엔티티 및 아키텍처 변수명 일치 수정

---

build.gradle
src/main/java/com/quokka/classmate/controller/SubjectController.java
src/main/resources/templates/main.html
src/test/java/com/quokka/classmate/controller/SubjectControllerTest.java
src/test/java/com/quokka/classmate/repository/SubjectRepositoryTest.java
src/test/java/com/quokka/classmate/service/SubjectServiceTest.java

1차 수강신청 페이지 컴포넌트 디자인 및 타임리프 문법 적용 완료

Feature kdj subject client

---

src/main/java/com/quokka/classmate/controller/RegisteredSubjectController.java
src/main/java/com/quokka/classmate/domain/dto/CartResponseDto.java
src/main/java/com/quokka/classmate/domain/entity/RegisteredSubject.java
src/main/java/com/quokka/classmate/domain/entity/Student.java
src/main/java/com/quokka/classmate/repository/RegisteredSubjectRepository.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java
src/main/resources/templates/cart.html

1. 장바구니 엔티티 추가
2. 장바구니 페이지 구현
3. 장바구니 수강 신청 버튼 추가
**아직 장바구니에서 '수강 신청' 기능은 구현 되어있지 않습니다.**
테스트 코드는 아직 작성 되어있지 않습니다.

Feature ksy registered subject

---

src/test/java/com/quokka/classmate/repository/SubjectRepositoryTest.java

test: 레포지토리 테스트 주석 처리

---

src/main/java/com/quokka/classmate/deploy/StatusCheckController.java
src/main/resources/templates/main.html

Feature kdj cart additional

---

src/main/java/com/quokka/classmate/controller/RegisteredSubjectController.java
src/main/java/com/quokka/classmate/domain/dto/SubjectResponseDto.java
src/main/java/com/quokka/classmate/domain/entity/RegisteredSubject.java
src/main/java/com/quokka/classmate/repository/RegisteredSubjectRepository.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java
src/main/resources/templates/main.html
src/test/java/com/quokka/classmate/controller/RegisteredSubjectControllerTest.java
src/test/java/com/quokka/classmate/controller/SubjectControllerTest.java
src/test/java/com/quokka/classmate/repository/RegisteredSubjectRepositoryTest.java
src/test/java/com/quokka/classmate/service/RegisteredSubjectServiceTest.java

Feature kdj cart function

---

src/main/java/com/quokka/classmate/controller/RegisteredSubjectController.java
src/main/java/com/quokka/classmate/domain/dto/CartResponseDto.java
src/main/java/com/quokka/classmate/domain/entity/RegisteredSubject.java
src/main/java/com/quokka/classmate/domain/entity/Student.java
src/main/java/com/quokka/classmate/domain/entity/Subject.java
src/main/java/com/quokka/classmate/global/constant/GlobalVariables.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java
src/main/java/com/quokka/classmate/service/StudentService.java
src/main/resources/templates/cart.html

장바구니에 담은 강의 수강신청 및 삭제 기능 구현되었습니다.
테스트 코드는 작성 예정입니다.

Feature ksy cart register subject

---

build.gradle
src/test/java/com/quokka/classmate/controller/RegisteredSubjectControllerTest.java
src/test/java/com/quokka/classmate/repository/RegisteredSubjectRepositoryTest.java
src/test/java/com/quokka/classmate/repository/SubjectRepositoryTest.java

Feature kdj register test

---

build.gradle
src/main/java/com/quokka/classmate/ClassmateApplication.java
src/main/java/com/quokka/classmate/global/security/UserDetailsServiceImpl.java
src/test/java/com/quokka/classmate/repository/RegisteredSubjectRepositoryTest.java
src/test/java/com/quokka/classmate/repository/StudentRepositoryTest.java
src/test/java/com/quokka/classmate/repository/SubjectRepositoryTest.java

- 로그인 처리에 따른 쿼리문 중복 출력 문제 캐싱 의존성으로 처리

Feature kdj refactoring login

---

src/main/java/com/quokka/classmate/controller/RegisteredSubjectController.java
src/main/java/com/quokka/classmate/controller/api/RegisteredSubjectApiController.java
src/main/java/com/quokka/classmate/global/exception/ApiResponseDto.java
src/main/java/com/quokka/classmate/global/exception/GlobalExceptionHandler.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java
src/main/resources/templates/cart.html

1. 수강 신청 기능 API 분리 하였습니다.
2. GlobalExceptionHandler 작성 하였습니다.

refactor: 수강 신청 기능 API 분리

---

src/main/java/com/quokka/classmate/controller/StaticController.java
src/main/java/com/quokka/classmate/controller/SubjectController.java
src/main/java/com/quokka/classmate/service/SubjectService.java
src/main/resources/templates/main.html
src/test/java/com/quokka/classmate/controller/SubjectControllerTest.java
src/test/java/com/quokka/classmate/service/SubjectServiceTest.java

- 정적 페이지 반환 담당
- `@Controller` 어노테이션 할당
- 반환 타입 `ResponseEntity`로 통일
- `@RestController` 어노테이션 할당

Feature kdj seperate

---

src/main/java/com/quokka/classmate/controller/RegisteredSubjectController.java
src/main/java/com/quokka/classmate/controller/api/RegisteredSubjectApiController.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java
src/main/resources/templates/cart.html
src/main/resources/templates/main.html

1. 장바구니 담기 API 분리
2. 장바구니 삭제 API 분리

refactor: 장바구니 담기, 장바구니 삭제 API 분리

---

src/main/java/com/quokka/classmate/controller/RegisteredSubjectController.java
src/main/java/com/quokka/classmate/domain/entity/Student.java
src/main/java/com/quokka/classmate/domain/entity/Subject.java
src/main/java/com/quokka/classmate/facade/RedissonLockFacade.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java
src/main/java/com/quokka/classmate/service/SubjectService.java

1. 수강 신청 시, 학생 학점 더하기 안되는 문제 수정 (메서드 추가)

fix: 수강 신청 시, 학점 더하기 메서드 추가

---

src/main/java/com/quokka/classmate/controller/RegisteredSubjectController.java
src/main/java/com/quokka/classmate/domain/entity/Student.java
src/main/java/com/quokka/classmate/domain/entity/Subject.java
src/main/java/com/quokka/classmate/facade/RedissonLockFacade.java
src/main/java/com/quokka/classmate/global/security/UserDetailsServiceImpl.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java
src/main/java/com/quokka/classmate/service/SubjectService.java

fix: 수강신청 시, 학생 정보에 학점 더해지지 않던 문제 수정

fix: 수강신청 시, 학생 정보에 학점 더해지지 않던 문제 수정

---

src/main/java/com/quokka/classmate/controller/api/RegisteredSubjectApiController.java

refactor: redisson 분산 락 -> 비관 락으로 변경

---

src/main/java/com/quokka/classmate/repository/RegisteredSubjectRepository.java

refactor: 장바구니 / 마이페이지 fetch join 적용하여 N+1 문제 개선

---

src/main/java/com/quokka/classmate/controller/api/RegisteredSubjectApiController.java
src/main/java/com/quokka/classmate/repository/RegisteredSubjectRepository.java

장바구니, 프로필 N+1 fetch join 개선 dev -> main merge

refactor: 장바구니, 프로필 N+1 fetch join 개선 dev -> main merge

---

src/main/java/com/quokka/classmate/controller/api/SubjectApiController.java
src/main/java/com/quokka/classmate/domain/entity/Subject.java
src/main/java/com/quokka/classmate/repository/SubjectRepository.java
src/main/java/com/quokka/classmate/service/SubjectService.java
src/main/resources/templates/main.html

Feature lsh pagination

---

src/main/java/com/quokka/classmate/controller/api/RegisteredSubjectApiController.java
src/main/java/com/quokka/classmate/facade/RegistrationCacheFacade.java
src/main/java/com/quokka/classmate/global/config/RedisConfig.java
src/main/java/com/quokka/classmate/repository/RedisRepository.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java

Feature ksy registration redis cache

---

src/main/java/com/quokka/classmate/global/config/RedisConfig.java

RedisConfig -> password 인증 추가 하였습니다

fix: Redis 인증 이슈 수정, RedisConfig password 정보 추가

---

src/main/java/com/quokka/classmate/controller/api/RegisteredSubjectApiController.java

Redis 캐시와 비교를 위하여, 수강신청 Redis 캐시 -> 비관적 락 으로 재변경 (Redis 캐시 미적용으로 변경)

refactor: Redis 캐시와 비교를 위하여, 수강신청 Redis 캐시 -> 비관적 락 으로 재변경

---

src/main/java/com/quokka/classmate/controller/api/RegisteredSubjectApiController.java
src/main/java/com/quokka/classmate/global/config/RedisConfig.java

Redis 캐시와 비교를 위하여, 수강신청 Redis 캐시 -> 비관적 락 으로 재변경 (Redis 캐시 미적용으로 변경)

Redis 캐시와 비교를 위하여, 수강신청 Redis 캐시 -> 비관적 락 으로 재변경 (Redis 캐시 미적용으로 변경)

---

src/main/java/com/quokka/classmate/event/EventScheduler.java

Reverts quokkaX2/classmate#111

Revert "fix: scheduler 주기 1초로 변경"

---

src/main/java/com/quokka/classmate/event/EventScheduler.java
src/main/java/com/quokka/classmate/service/QueueService.java

Reverts quokkaX2/classmate#110

Revert "fix: scheduler 주기와 레디스 처리량 증가"

---

src/main/java/com/quokka/classmate/controller/api/RegisteredSubjectApiController.java
src/main/java/com/quokka/classmate/domain/entity/Student.java
src/main/java/com/quokka/classmate/domain/entity/Subject.java
src/main/java/com/quokka/classmate/repository/RedisRepository.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java
src/main/resources/templates/cart.html
src/main/resources/templates/profile.html

1. 수강신청 취소 기능 구현
2. 수강신청 버튼, 장바구니 삭제 버튼 id값 중복으로 작동 안되던 버그 fix - script 수정

feat: 수강신청 취소 기능 구현

---

build.gradle
src/main/java/com/quokka/classmate/ClassmateApplication.java

Reverts quokkaX2/classmate#181

Revert "fix: shedlock version upgrade"

---

src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java

과목 잔여 자리 수 감소 더티체킹만 하도록 변경 (save 메서드 지움)

fix: 수강신청시 과목 잔여 자리 수 감소 더티체킹만 하도록 변경

---

src/main/java/com/quokka/classmate/repository/SearchSubjectRepositoryImpl.java
src/main/java/com/quokka/classmate/service/RegisteredSubjectService.java

과목 잔여 자리 수 더티체킹만 하도록 변경

---

build.gradle
src/main/java/com/quokka/classmate/ClassmateApplication.java
src/main/java/com/quokka/classmate/event/EventScheduler.java
src/main/java/com/quokka/classmate/global/config/SchedLockConfig.java

feat: 스케줄러 락 적용

---

src/main/java/com/quokka/classmate/global/config/ElasticConfig.java

Reverts quokkaX2/classmate#188

Revert "elastic 인증 제외"

---

src/main/java/com/quokka/classmate/global/config/ElasticConfig.java

Reverts quokkaX2/classmate#187

Revert "feat: elasticsearch 인증 제외"

---

src/main/java/com/quokka/classmate/global/config/ElasticConfig.java

Reverts quokkaX2/classmate#199

Revert "elasticsearch 인증 제외"

---

src/main/java/com/quokka/classmate/global/config/ElasticConfig.java

Reverts quokkaX2/classmate#200

Revert "Revert "elasticsearch 인증 제외""
